### ISSUE TITLE
The 502 bad issue

### ISSUE THREAD

**Issue by mis3250** [aws-samples/real-time-analytics-with-apache-pinot-on-aws#1]
I have followed the guide to deploy the pinot cloudformation template with cdk. And the cloudformation template is successfully implemented. However, I cannot visit the controller. the browser gives me the 502 bad gateway message. Would you please take a look? Thank you very much for your attention.

**Comment by mis3250** [comment]
![image](https://github.com/user-attachments/assets/9fb7a38d-5763-4b57-891a-ee5fce4301da)

**Comment by mis3250** [comment]
![image](https://github.com/user-attachments/assets/8edadb81-c5d6-436b-adc2-d5c2e9068e6f)

**Comment by fmorillo7694** [comment]
We had to update to Pinot latest version as they removed version 0.12.2.
